### PR TITLE
Create 2.1

### PR DESCRIPTION
**Pull request by sanya099**
please check my code

### CODE REVIEW

**Review by Sakshi785 — CHANGES_REQUESTED** [review]
correct the code

**Comment by sanya099** [comment]
okkk thank uuu

**Comment by Sakshi785** [comment]
kara code correct ki nahi??

**Comment by Sakshi785** [comment]
BCAC

**Comment by sanya099** [comment]
abeyy chu**ya code glt kb tha

**Comment by Sakshi785** [comment]
BC ye code sahi kab tha

**Pull request merged**
